[package]
name = "TP0"
version = "0.1.0"
edition = "2024"
default-run = "TP0"

[[bin]]
name = "tp1"
path = "src/tp1.rs"

[[bin]]
name = "ecrivain"
path = "src/ecrivain.rs"

[[bin]]
name = "analyseur_trame"
path = "src/analyseur_trame.rs"

[dependencies]
