[package]
name = "TP0"
version = "0.1.0"
edition = "2024"
default-run = "TP0"

[[bin]]
name = "tp1"
path = "src/tp1.rs"

[[bin]]
name = "gestionnaire_fichiers"
path = "src/gestionnaire_fichiers.rs"

[dependencies]
chrono = "0.4"
